spring:
  application:
    name: spring-kafka-test

  config:
    import: optional:file:.env[.properties]

  kafka:
    bootstrap-servers: ${KAFKA_BROKER_URL}
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required
            username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";

    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        enable:
          idempotence: false

    consumer:
      auto-offset-reset: latest
      group-id: ${KAFKA_USERNAME}-consumers
      properties:
        spring:
          json:
            trusted:
              packages: com.malex
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


cloud:
  kafka:
    topic: ${KAFKA_USERNAME}-default
    topic_input: ${KAFKA_USERNAME}-input
    topic_output: ${KAFKA_USERNAME}-output