server:
  port: ${APP_SERVICE_PORT:0}

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: ${APP_SERVICE_NAME:kafka-batch-producer}

kafka:
  topic:
    out: ${KAFKA_USERNAME}-json-producer
  server:
    bootstrapServer: ${KAFKA_BROKER_URL}
    propertySecurityProtocol: SASL_SSL
    propertySaslMechanism: SCRAM-SHA-256
    propertySaslJaasConfig: org.apache.kafka.common.security.scram.ScramLoginModule required
      username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
  producer:
    keySerializer: org.apache.kafka.common.serialization.StringSerializer
    valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer
    propertyEnableIdempotence: false
    propertySpringJsonAddTypeHeaders: false