server:
  port: ${APP_SERVICE_PORT:0}

spring:
  application:
    name: ${APP_SERVICE_NAME:consumer-error-handler}

  config:
    import: optional:file:.env[.properties]

  kafka:
    #    bootstrap-servers: ${KAFKA_BROKER_URL}
    #    properties:
    #      security:
    #        protocol: SASL_SSL
    #      sasl:
    #        mechanism: SCRAM-SHA-256
    #        jaas:
    #          config: org.apache.kafka.common.security.scram.ScramLoginModule required
    #            username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";

    consumer:
      auto-offset-reset: latest
#      group-id: ${KAFKA_USERNAME}-consumers
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: com.malex
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka:
  bootstrap:
    servers:
      url: ${KAFKA_BROKER_URL}
  topic: ${KAFKA_USERNAME}-json-producer
  groupId: ${KAFKA_USERNAME}-consumer-error-handler
  security:
    sasl:
      protocol: SASL_SSL
      mechanism: SCRAM-SHA-256
      jaas:
        config: org.apache.kafka.common.security.scram.ScramLoginModule required
          username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
  default:
    enabled: true