server:
  port: ${APP_SERVICE_PORT:8082}

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: ${APP_SERVICE_NAME:kafka-producer}

  kafka:
    bootstrap-servers: ${CLOUD_KAFKA_BROKER_URL}
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required
            username="${CLOUD_KAFKA_USERNAME}" password="${CLOUD_KAFKA_PASSWORD}";

    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        enable:
          idempotence: false

cloud:
  kafka:
    topic: ${CLOUD_KAFKA_USERNAME}-default