server:
  port: ${APP_SERVICE_PORT:0}

spring:
  application:
    name: ${APP_SERVICE_NAME:reactor-consumer}

  config:
    import: optional:file:.env[.properties]

consumer:
  kafka:
    bootstrapServerUrl: ${KAFKA_BROKER_URL}
    topic: ${KAFKA_USERNAME}-json-producer
    groupId: ${KAFKA_USERNAME}-consumers
    securitySaslProtocol: SASL_SSL
    securitySaslMechanism: SCRAM-SHA-256
    securitySaslJaasConfig: org.apache.kafka.common.security.scram.ScramLoginModule required
      username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
